version: "3"
services: 
  mongodb:
    container_name: saturn-service-mongodb
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: saturn-service-api
    build: ./docker/Dockerfile .
    restart: always
    image: saturn-service-api
    command: npm start
    volumes: 
      - ./dist:/usr/app/dist
    ports:
      - "3001:3001"
    links:
      - mongodb