export enum ErrorsTypeEnum {
  NOT_FOUND = 'NOT_FOUND',
  INVALID_PARAM_ERROR = 'INVALID_PARAM_ERROR',
  MISSING_MANDATORY_PARAM_ERROR = 'MISSING_MANDATORY_PARAM_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
  EMAIL_IS_ALREADY_USE = 'EMAIL_IS_ALREADY_USE',
  ACCESS_DENIED_ERROR = 'ACCESS_DENIED_ERROR',
  INVALID_DATE_ERROR = 'INVALID_DATE_ERROR'
}
