name: Open Pull Request

on: [pull_request]

jobs:
  name: Installing Packages
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hasFiles('**/package-lock')}}

    - name: Install dependencies
      run: npm install

unusedImport:
  name: Find unused import (dead code)
  runs-on: ubuntu-latest
  needs: install
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hasFiles('**/package-lock')}}

    - name: Install dependencies
      run: npm install

    - name: Run ts-prune
      run: npm run ts-prune --error
