name: Open Pull Request

on: [pull_request]

jobs:
  install: Installing Packages
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hasFiles('**/package-lock')}}

    - name: Install dependencies
      run: npm install
